/// key_get_name(key)

if (getinput==argument0) return "<press key>";

switch(OPTIONS[argument0]) {
    case 0: return "<no key>";
    case vk_left: return "LEFT";
    case vk_right: return "RIGHT";
    case vk_up: return "UP";
    case vk_down: return "DOWN";
    case vk_backspace: return "BACKSPACE";
    case vk_enter: return "ENTER";
    case vk_add: return "+";
    case vk_lalt: return "LEFT ALT";
    case vk_ralt: return "RIGHT ALT";
    case vk_lcontrol: return "LEFT CONTROL";
    case vk_rcontrol: return "RIGHT CONTROL";
    case vk_lshift: return "LEFT SHIFT";
    case vk_rshift: return "RIGHT SHIFT";
    case vk_escape: return "ESCAPE";
    case vk_f1: return "F1";
    case vk_f2: return "F2";
    case vk_f3: return "F3";
    case vk_f4: return "F4";
    case vk_f5: return "F5";
    case vk_f6: return "F6";
    case vk_f7: return "F7";
    case vk_f8: return "F8";
    case vk_f9: return "F9";
    case vk_f10: return "F10";
    case vk_f11: return "F11";
    case vk_f12: return "F12";
    case vk_home: return "HOME";
    case vk_end: return "END";
    case vk_pagedown: return "PAGE DOWN";
    case vk_pageup: return "PAGE UP";
    case vk_tab: return "TAB";
    case vk_pause: return "PAUSE";
    case vk_printscreen: return "PRINT SCREEN";
    case vk_insert: return "INSERT";
    case vk_delete: return "DELETE";
    case vk_decimal: return "DECIMAL";
    case vk_divide: return "/";
    case vk_multiply: return "*";
    case vk_subtract: return "-";
    case vk_space: return "SPACE";
    case vk_numpad0: return "NUMPAD 0";
    case vk_numpad1: return "NUMPAD 1";
    case vk_numpad2: return "NUMPAD 2";
    case vk_numpad3: return "NUMPAD 3";
    case vk_numpad4: return "NUMPAD 4";
    case vk_numpad5: return "NUMPAD 5";
    case vk_numpad6: return "NUMPAD 6";
    case vk_numpad7: return "NUMPAD 7";
    case vk_numpad8: return "NUMPAD 8";
    case vk_numpad9: return "NUMPAD 9";
    case 144: return "NUM LOCK";
    case 20: return "CAPS LOCK";
    case 226: return "\";
    case 188: return ",";
    case 190: return ".";
    case 191: return ";";
    case 187: return "=";
    case 91: return "WINDOWS KEY";
    case 93: return "MENU KEY";
    case 192: return "'";
    case 12: return "???";
    case gp_face1: return cond(string_count("PLAYSTATION", gamepad_get_description(0)), "PS CROSS", "XBOX A");
    case gp_face2: return cond(string_count("PLAYSTATION", gamepad_get_description(0)), "PS CIRCLE", "XBOX B");
    case gp_face3: return cond(string_count("PLAYSTATION", gamepad_get_description(0)), "PS SQUARE", "XBOX X");
    case gp_face4: return cond(string_count("PLAYSTATION", gamepad_get_description(0)), "PS TRIANGLE", "XBOX Y");
    case gp_shoulderl: return "LEFT SHOULDER";
    case gp_shoulderr: return "RIGHT SHOULDER";
    case gp_shoulderlb: return "LEFT TRIGGER";
    case gp_shoulderrb: return "RIGHT TRIGGER";
    case gp_select: return "SELECT";
    case gp_start: return "START";
    case gp_stickl: return "L3";
    case gp_stickr: return "R3";
    case gp_padu: return "D-PAD UP";
    case gp_padd: return "D-PAD DOWN";
    case gp_padl: return "D-PAD LEFT";
    case gp_padr: return "D-PAD RIGHT";
    default: return chr(OPTIONS[argument0]);
}
